# Copyright 2026 Ori Nexus Systems LTD
# SPDX-License-Identifier: Apache-2.0

"""Public package surface for ori-sdk-python."""

from ori_sdk.errors import (
    GatewayContractError,
    HealthClientError,
    OriSDKError,
    SkillMetadataValidationError,
)
from ori_sdk.firmware_telemetry import (
    FIRMWARE_DEVICE_ID_MAX_LENGTH,
    FIRMWARE_FAULT_TOKEN_MAX_LENGTH,
    FIRMWARE_JSON_SAFE_INT_MAX,
    FIRMWARE_SIGNATURE_ALGORITHM,
    FIRMWARE_SIGNATURE_PREFIX,
    FIRMWARE_TELEMETRY_VERSION,
    FirmwareActionAuthority,
    FirmwareCapabilityManifest,
    FirmwareChannelProtocol,
    FirmwareDeviceMode,
    FirmwareErrorCode,
    FirmwareFaultCode,
    FirmwareFaultEvent,
    FirmwareFreshnessState,
    FirmwareFreshnessVerdict,
    FirmwareHeartbeatEnvelope,
    FirmwareKeyStorage,
    FirmwareManifestAction,
    FirmwareManifestChannel,
    FirmwareManifestInterlock,
    FirmwarePosture,
    FirmwareProvisioningAnchor,
    FirmwareSequencedPayload,
    FirmwareTelemetryEnvelope,
    FirmwareTelemetryError,
    FirmwareTelemetryReading,
    FirmwareTransport,
    FirmwareUnsignedPayload,
    SignedFirmwareCapabilityManifest,
    SignedFirmwareFaultEvent,
    SignedFirmwareHeartbeat,
    SignedFirmwareTelemetry,
    canonical_firmware_json_bytes,
    evaluate_firmware_freshness,
    firmware_manifest_hash,
    parse_signed_firmware_telemetry,
    verify_firmware_fault_event,
    verify_firmware_heartbeat,
    verify_firmware_manifest,
    verify_firmware_signature,
    verify_firmware_telemetry,
)
from ori_sdk.gateway import (
    GATEWAY_HEALTH_TOPIC,
    GATEWAY_REASONING_REQUEST_TOPIC_FILTER,
    RUNTIME_NODE_HEARTBEAT_TOPIC_FILTER,
    TIER_C_ENRICHMENT_REQUEST_TOPIC_FILTER,
    GatewayRetryPolicy,
    build_gateway_reasoning_request,
    export_request_topic,
    export_response_topic,
    export_response_topic_filter,
    gateway_request_topic,
    gateway_response_topic,
    new_request_id,
    parse_gateway_reasoning_response,
    response_matches_request,
    runtime_node_heartbeat_topic,
    tier_c_enrichment_request_topic,
    tier_c_enrichment_response_topic,
    validate_export_response,
    validate_response,
    validate_tier_c_enrichment_response,
)
from ori_sdk.gateway_models import (
    ExportType,
    JsonObject,
    JsonScalar,
    JsonValue,
    RuntimeExportRequest,
    RuntimeExportResponse,
    RuntimeNodeHeartbeat,
    RuntimeNodeHeartbeatEvidence,
    RuntimeNodeStatus,
    TierCEnrichmentHistorySample,
    TierCEnrichmentRequest,
    TierCEnrichmentResponse,
)
from ori_sdk.health import RuntimeHealthClient
from ori_sdk.helpers import (
    PostureReport,
    StalenessReport,
    error_code_from_health_failure,
    posture_interpretation,
    staleness_summary,
)
from ori_sdk.models import (
    AlertTimestamps,
    CapabilityPosture,
    DevicePolicyState,
    GatewayContextHistoryPoint,
    GatewayReasoningContext,
    GatewayReasoningRequest,
    GatewayReasoningResponse,
    HealthError,
    HealthResponse,
    HealthStatus,
    SensorStatus,
)
from ori_sdk.skill_package import (
    ActionRef,
    ActionsSection,
    ActionTier,
    EscalationTier,
    ReasoningPolicy,
    SensorRequirement,
    SkillPackage,
    SkillYamlNormaliser,
    Trigger,
)
from ori_sdk.telemetry import (
    JSON_SAFE_INT_MAX,
    RUNTIME_TELEMETRY_SCHEMA_VERSION,
    RuntimeTelemetryBatch,
    RuntimeTelemetryEvent,
    RuntimeTelemetryEventType,
    RuntimeTelemetryReading,
    TelemetryCanonicalizationError,
    TelemetryJsonObject,
    TelemetryJsonScalar,
    TelemetryJsonValue,
    canonical_telemetry_bytes,
    telemetry_hmac_sha256,
)
from ori_sdk.validation import validate_skill_metadata, validate_skill_metadata_file

__all__ = [
    # errors
    "GatewayContractError",
    "HealthClientError",
    "OriSDKError",
    "SkillMetadataValidationError",
    # firmware telemetry
    "FIRMWARE_DEVICE_ID_MAX_LENGTH",
    "FIRMWARE_FAULT_TOKEN_MAX_LENGTH",
    "FIRMWARE_JSON_SAFE_INT_MAX",
    "FIRMWARE_SIGNATURE_ALGORITHM",
    "FIRMWARE_SIGNATURE_PREFIX",
    "FIRMWARE_TELEMETRY_VERSION",
    "FirmwareActionAuthority",
    "FirmwareCapabilityManifest",
    "FirmwareChannelProtocol",
    "FirmwareDeviceMode",
    "FirmwareErrorCode",
    "FirmwareFaultCode",
    "FirmwareFaultEvent",
    "FirmwareFreshnessState",
    "FirmwareFreshnessVerdict",
    "FirmwareHeartbeatEnvelope",
    "FirmwareKeyStorage",
    "FirmwareManifestAction",
    "FirmwareManifestChannel",
    "FirmwareManifestInterlock",
    "FirmwarePosture",
    "FirmwareProvisioningAnchor",
    "FirmwareSequencedPayload",
    "FirmwareTelemetryEnvelope",
    "FirmwareTelemetryError",
    "FirmwareTelemetryReading",
    "FirmwareTransport",
    "FirmwareUnsignedPayload",
    "SignedFirmwareCapabilityManifest",
    "SignedFirmwareFaultEvent",
    "SignedFirmwareHeartbeat",
    "SignedFirmwareTelemetry",
    "canonical_firmware_json_bytes",
    "evaluate_firmware_freshness",
    "firmware_manifest_hash",
    "parse_signed_firmware_telemetry",
    "verify_firmware_fault_event",
    "verify_firmware_heartbeat",
    "verify_firmware_manifest",
    "verify_firmware_signature",
    "verify_firmware_telemetry",
    # gateway
    "GATEWAY_HEALTH_TOPIC",
    "GATEWAY_REASONING_REQUEST_TOPIC_FILTER",
    "RUNTIME_NODE_HEARTBEAT_TOPIC_FILTER",
    "TIER_C_ENRICHMENT_REQUEST_TOPIC_FILTER",
    "GatewayRetryPolicy",
    "build_gateway_reasoning_request",
    "export_request_topic",
    "export_response_topic",
    "export_response_topic_filter",
    "gateway_request_topic",
    "gateway_response_topic",
    "new_request_id",
    "parse_gateway_reasoning_response",
    "response_matches_request",
    "runtime_node_heartbeat_topic",
    "tier_c_enrichment_request_topic",
    "tier_c_enrichment_response_topic",
    "validate_export_response",
    "validate_response",
    "validate_tier_c_enrichment_response",
    # gateway models
    "ExportType",
    "JsonObject",
    "JsonScalar",
    "JsonValue",
    "RuntimeExportRequest",
    "RuntimeExportResponse",
    "RuntimeNodeHeartbeat",
    "RuntimeNodeHeartbeatEvidence",
    "RuntimeNodeStatus",
    "TierCEnrichmentHistorySample",
    "TierCEnrichmentRequest",
    "TierCEnrichmentResponse",
    # health client
    "RuntimeHealthClient",
    # helpers
    "PostureReport",
    "StalenessReport",
    "error_code_from_health_failure",
    "posture_interpretation",
    "staleness_summary",
    # models
    "AlertTimestamps",
    "CapabilityPosture",
    "DevicePolicyState",
    "GatewayContextHistoryPoint",
    "GatewayReasoningContext",
    "GatewayReasoningRequest",
    "GatewayReasoningResponse",
    "HealthError",
    "HealthResponse",
    "HealthStatus",
    "SensorStatus",
    # skill package
    "ActionRef",
    "ActionTier",
    "ActionsSection",
    "EscalationTier",
    "ReasoningPolicy",
    "SensorRequirement",
    "SkillPackage",
    "SkillYamlNormaliser",
    "Trigger",
    # direct runtime telemetry
    "JSON_SAFE_INT_MAX",
    "RUNTIME_TELEMETRY_SCHEMA_VERSION",
    "RuntimeTelemetryBatch",
    "RuntimeTelemetryEvent",
    "RuntimeTelemetryEventType",
    "RuntimeTelemetryReading",
    "TelemetryCanonicalizationError",
    "TelemetryJsonObject",
    "TelemetryJsonScalar",
    "TelemetryJsonValue",
    "canonical_telemetry_bytes",
    "telemetry_hmac_sha256",
    # validation
    "validate_skill_metadata",
    "validate_skill_metadata_file",
]
